import { Inter } from "next/font/google";
import "./../globals.css";
import Navbar from "./layouts/Navbar";
import Sidebar from "./layouts/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
    return (
        // <html lang="en">
        //     <body className={inter.className} >
            <> 
                <div 
                    style={{
                        marginLeft: "280px",
                        height: "60px",
                        width: "100%",
                    }}
                >
                    <Navbar />
                </div>
                <div 
                    style={{
                        position: "fixed",
                        top: '0px',
                        height: "100vh",
                        background: '#fff',
                    }}
                >
                    <Sidebar />
                </div>
                <div 
                    style={{
                        marginLeft: "280px",
                    }}
                >
                    {children}
                </div>
            </>
        //     </body>
        // </html>
    );
}
